allow specifying the `i2c_bus` on neoKey and neoTrellis
adafruit/Adafruit_Seesaw pull request #63
Opened 2022-01-24 11:05 UTC by rltvty

This change is to allow specifying the `i2c_bus` on neoKey and neoTrellis initialization.

This was done to allow the use of these libraries with boards like the Adafruit Feather RP2040, where the stemma connector is on `Wire1` instead of `Wire0`.

Specifically for use with the Adafruit Feather RP2040, the following is required to use these libraries:
```
  // setup i2c for Adafruit Feather RP2040
  Wire1.setSDA(2);
  Wire1.setSCL(3);

  //setup neokey on Wire1
  neokey = Adafruit_NeoKey_1x4(NEOKEY_1X4_ADDR, &Wire1);
  neokey.begin()

  // setup neotrellis on Wire1
  trellis = Adafruit_NeoTrellis(NEO_TRELLIS_ADDR, &Wire1);
  trellis.begin()
```

After the above changes are applied, the examples should work as normal on the Adafruit Feather RP2040 board.

(sorry for the 4 separate commits, I made the changes directly on GitHub)

2022-01-24 17:42 UTC, ladyada requested changes

2022-01-24 17:42 UTC, ladyada commented on Adafruit_NeoTrellis.h
> +  Adafruit_NeoTrellis(uint8_t addr = NEO_TRELLIS_ADDR, TwoWire *i2c_bus = NULL);
hiya just one change, instead of NULL default to &Wire?

2022-01-26 00:11 UTC, rltvty commented on Adafruit_NeoTrellis.h
> +  Adafruit_NeoTrellis(uint8_t addr = NEO_TRELLIS_ADDR, TwoWire *i2c_bus = NULL);
should be ready now

2022-01-26 01:55 UTC, ladyada approved these changes
awesome thanks! :)

2022-01-26 01:55 UTC, merged